In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("0000000000002429_training_titanic_x_y_train.csv")
print(df.shape)
print(df.describe())
df.isnull().sum()


(668, 11)
           Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000


Pclass        0
Name          0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [2]:
df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [3]:
def f1(s):
    if s=="female":
        return 0
    else:
        return 1
def f2(s):
    if s=='S':
        return 1
    elif s=='Q':
        return 2
    else:
        return 3
def f3(n):
    return n


In [4]:
df.Age.fillna(df.Age.mean(),inplace=True)
df.describe()
df["Sex_numeric"]=df.Sex.apply(f1)
df["Embarked_numeric"]=df.Embarked.apply(f2)
df["survived_numeric"]=df.Survived.apply(f3)
del df['Name']
del df['Cabin']
del df['Ticket']
del df['Survived']
del df['Embarked']
del df['Sex']
df.head()

Pclass       Age  SibSp  Parch    Fare  Sex_numeric  Embarked_numeric  \
0       2  29.00000      1      0  26.000            0                 1   
1       3  29.70056      0      0   8.050            1                 1   
2       2  39.00000      0      0  26.000            1                 1   
3       3  29.00000      0      4  21.075            0                 1   
4       3  25.00000      0      0   7.050            1                 1   

   survived_numeric  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [5]:
df.dtypes

Pclass                int64
Age                 float64
SibSp                 int64
Parch                 int64
Fare                float64
Sex_numeric           int64
Embarked_numeric      int64
survived_numeric      int64
dtype: object

In [6]:
train_data=np.array(df,int)
train_data
print(train_data)
x_train=train_data[:,:-1]
y_train=train_data[:,-1]
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train,y_train)

[[ 2 29  1 ...  0  1  1]
 [ 3 29  0 ...  1  1  0]
 [ 2 39  0 ...  1  1  0]
 ...
 [ 3 32  0 ...  1  1  1]
 [ 3 22  0 ...  0  1  0]
 [ 3 29  1 ...  0  2  1]]


/Users/sankalpaggarwal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
df2=pd.read_csv("0000000000002429_test_titanic_x_test.csv")
print(df2.shape)
print(df2.describe())
df2.isnull().sum()

(223, 10)
           Pclass         Age       SibSp       Parch        Fare
count  223.000000  178.000000  223.000000  223.000000  223.000000
mean     2.345291   29.694775    0.506726    0.304933   32.622551
std      0.850047   15.398053    1.169700    0.634108   61.062047
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   19.250000    0.000000    0.000000    7.879200
50%      3.000000   27.000000    0.000000    0.000000   12.475000
75%      3.000000   37.750000    1.000000    0.000000   30.035400
max      3.000000   71.000000    8.000000    2.000000  512.329200


Pclass        0
Name          0
Sex           0
Age          45
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       173
Embarked      1
dtype: int64

In [8]:
df2.Age.fillna(df2.Age.mean(),inplace=True)
df2.describe()
df2["Sex_numeric"]=df2.Sex.apply(f1)
df2["Embarked_numeric"]=df2.Embarked.apply(f2)
del df2['Name']
del df2['Cabin']
del df2['Ticket']
del df2['Embarked']
del df2['Sex']
df2.head()

Pclass        Age  SibSp  Parch     Fare  Sex_numeric  Embarked_numeric
0       2   8.000000      1      1  36.7500            1                 1
1       1  49.000000      0      0  25.9292            0                 1
2       3  29.694775      0      0   7.7375            1                 2
3       2  24.000000      2      1  27.0000            0                 1
4       1  36.000000      0      0  26.2875            1                 1

In [9]:
test_data=np.array(df2,int)
print(test_data)
x_test=test_data[:,:]
y_pred=clf.predict(x_test)

[[  2   8   1 ...  36   1   1]
 [  1  49   0 ...  25   0   1]
 [  3  29   0 ...   7   1   2]
 ...
 [  1  17   1 ... 108   0   3]
 [  3  43   0 ...   6   1   1]
 [  2  36   0 ...  26   1   1]]


In [10]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0])

In [11]:
y_pred=y_pred.reshape(-1,1)

In [12]:
np.savetxt("output_logistic_titanic.csv",y_pred)